### ISSUE TITLE
TLS/SSL Support

### ISSUE THREAD

**Issue by aklinker1** [aklinker1/miasma#30]
Curious how hard this would be to add, I think it would work well as a plugin.

Here's a guide for Nginx instead of Traefik: https://finnian.io/blog/ssl-with-docker-swarm-lets-encrypt-and-nginx/

**Comment by prologic** [comment]
This project already has a [Traefik plugin](https://aklinker1.github.io/miasma/plugins/traefik.html) which Traefik itself has full support for Let's Encrypt with HTTP and DNS challenges. So I don't think we need to build another way to do TLS/SSL.

**Comment by aklinker1** [comment]
Oh nice, I had yet to look into the traefik aspect of it.

**Comment by prologic** [comment]
> Oh nice, I had yet to look into the traefik aspect of it.

Traefik itself is pretty nice. +1 on including it and making it a plugin. If done right, it would be what I'd call generally the "ingress" plugin 👌 Other pluggable ingress choices could be: nginx, caddy, etc.

**Comment by aklinker1** [comment]
Yup, I tried out Nginx initially, but Traefik was basically 0 config for docker swarm, so it fit right in. I'd be interested to know what else it needs to do before you'd consider it an ingress plugin.

I initially considered naming it the "ingress" plugin, but decided to go with the image name for now until I have a second plugin, and decide on a naming convention then. Right now, it's looking like a built-in docker registry will be the second plugin, so apps auto-update when you push images to it.

**Comment by prologic** [comment]
I think the main two things you want to be able to provide are:

- Configuring the TLS / Let's Encrypt parts of Traefik
- Adding domains (see above)
- Adding custom routes

The rest (routes) should be handled automatically by Docker Swarm service labels.

**Comment by aklinker1** [comment]
> - Adding custom routes

What do you mean by different custom routes? Is that different than `domain.com/path`?

**Comment by prologic** [comment]
> > * Adding custom routes
> 
> What do you mean by different custom routes? Is that different than `domain.com/path`?

Yeap! You just never know when you _might_ want to add arbitrary custom routes to Treafik that aren't otherwise automatically picked up routes from Docker Swarm labels from running services.

**Comment by aklinker1** [comment]
The plugin already supports custom routes then! See how I've setup `api-2` in the [example](https://aklinker1.github.io/miasma/plugins/traefik.html#example-usage):

```bash
miasma traefik:set -a api-2 --host web2.home.io --path /api
```

and it also supports raw traefik rules:

```bash
miasma traefik:set --rule "(Host('hostname') && PathPrefix('/custom-path'))"
```

So all that's left would be TLS. I've got time this weekend, I'd like to get the project to the point where I can deploy it on EC2 instances or Digitial Ocean droplets so I can start using it for my personal, public stuff. And this is all that's left before I can do that.

**Comment by prologic** [comment]
That sounds good to me!

Let mw know if you'd like s hand testing things. Be more than happy to give this a whirl once things are in shape 👌

**Comment by aklinker1** [comment]
Well... actually I also need to add authentication... I'll start simple with a env variable token lol

**Comment by aklinker1** [comment]
https://doc.traefik.io/traefik/https/acme/#configuration-examples

**Comment by aklinker1** [comment]
https://stackoverflow.com/questions/60510232/how-can-i-redirect-http-to-https-using-traefik#60513369

**Comment by aklinker1** [comment]
@prologic, HTTPS has been merged and published to the `aklinker1/miasma:nightly` image. If you want to test it out, now is the time!

Let me know if you have any issues, I've probably forgotten to document something.

**Comment by prologic** [comment]
Will do! Probably this weekend if that's okay? I have a lot of my own do job work to do 🤦‍♂️

**Comment by aklinker1** [comment]
No worries lol, I'm off today for 4th of July in the US.

**Comment by prologic** [comment]
> No worries lol, I'm off today for 4th of July in the US.

Happy 4th of July! 🥳
