### ISSUE TITLE
Installation fails on Ubuntu 20.04

### ISSUE THREAD

**Issue by prologic** [aklinker1/miasma#61]
This is mostly just an FYI. You _may_ want to document this somewhere:

```#!sh
root@test:~# curl -fsSL https://get.docker.com | bash -
# Executing docker install script, commit: b2e29ef7a9a89840d2333637f7d1900a83e7153f
+ sh -c 'apt-get update -qq >/dev/null'
E: Repository 'https://apprepo.vultr.com/ubuntu universal InRelease' changed its 'Codename' value from 'buster' to 'universal'
root@test:~# curl -fsSL https://get.docker.com | bash -
# Executing docker install script, commit: b2e29ef7a9a89840d2333637f7d1900a83e7153f
+ sh -c 'apt-get update -qq >/dev/null'
E: Repository 'https://apprepo.vultr.com/ubuntu universal InRelease' changed its 'Codename' value from 'buster' to 'universal'
```

I don't think you should even bother supporting anything as old as Ubuntu 20.04 anyway IMO.

**Comment by prologic** [comment]
In fact, I _think_ you should just assume Docker is installed and leave that up to the end-user. Unless you want to fully automate away the setup process?

**Comment by prologic** [comment]
For context I've been trying out several of these self-host / home cloud Docker-based "things" (yours included) and here are the results so far:

- miasma: Pending
- Umbrel: Insecure by default
- Cloudron: Installed ok, Login failed.
- CasaOS: Failed to install

**Comment by prologic** [comment]
In fact, this fails on Ubuntu 22.04 too 😳

```#!sh
root@test:~# curl -fsSL https://get.docker.com | sh -
# Executing docker install script, commit: b2e29ef7a9a89840d2333637f7d1900a83e7153f
+ sh -c apt-get update -qq >/dev/null
E: Repository 'https://apprepo.vultr.com/ubuntu universal InRelease' changed its 'Codename' value from 'buster' to 'universal'
root@test:~# uname -a
Linux test 5.15.0-40-generic #43-Ubuntu SMP Wed Jun 15 12:54:21 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
root@test:~# cat /etc/os-release | grep -i version
VERSION_ID="22.04"
VERSION="22.04.1 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
root@test:~#
```

I have a funny feeling upstream Docker have broken their Debian/Ubuntu package repository 😂 Faaaark me 🤦‍♂️

**Comment by prologic** [comment]
Actually... This _may_ be a problem with Vultr's Package mirrors. I've filed a support ticket. I'll close this issue if that's the case 👌

**Comment by aklinker1** [comment]
Yeah, it works for me with a fresh Ubuntu 20.04 install. Must be something to do with Vultr. You could try and [install docker any other way](https://github.com/aklinker1/miasma/commit/d8652087028d2ddc36f4355ede55e2d95169e998). The `get.docker.com` script is just the fewest lines to include in the setup process, because yes, installing docker should be left up to the user.

**Comment by prologic** [comment]
Yeah but I'm also lazy 😅 So...

I'll wait for Vultr to fix their shit and˚ try again.

Sorry I haven't tried miasma sooner like I promised 🤦‍♂️

**Comment by aklinker1** [comment]
Haha no worries :+1: 

Since this is an issue with installing docker, I'm gonna close this issue. Feel free to create a new one if you get stuck somewhere else.

**Comment by prologic** [comment]
Nah all good, this is not an issue with miasma per se. I'll report back somewhere on success or failure (file an issue)
